name: "rl_project"
type: "python:3.11"

relationships:
  
  database: "db:postgresql"

# The configuration of the app when it's exposed to the web.
web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET rl_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true

# The size of the persistent disk of the application (in MB).
disk: 512 

# Set a local read/write mount for logs.
mounts:
    "logs":
        source: local
        source_path: logs

# The hooks exeuted at varius points in the lifecycle of the application.
hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_remote.txt

        mkdir -p logs
        python manage.py collectstatic

    deploy: |
        python manage migrate
        gunicorn -w 4 -b unix:$SOCKET rl_project.wsgi:application --daemon
