# Generated by Django 4.2.6 on 2023-10-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_name',
            old_name='title',
            new_name='text',
        ),
    ]
