# Generated by Django 4.2.6 on 2023-11-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_log', '0004_recipe_name_owner'),
    ]

    operations = [
        
        migrations.RenameModel(
            old_name='Entry',
            new_name='RecipeDetails',
        ),
        migrations.RenameModel(
            old_name='Recipe_name',
            new_name='Recipe',
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_log.recipe'),
        ),
    ]
