# Generated by Django 4.2.6 on 2023-11-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_log', '0005_recipe_rename_entry_recipedetails_delete_recipe_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedetails',
            options={'verbose_name_plural': 'recipe_details'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Owner',
            new_name='owner',
        ),
    ]
